name: Post Release
'on':
  push:
    branches:
      - master
  workflow_dispatch: null
jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: "⏬ Checkout repository"
        uses: actions/checkout@v3
      - name: "\U0001F530 Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: "\U0001F4E6 Install dependencies"
        run: npm install
      - name: "\U0001F9EA Test and Coverage"
        run: npm run coverage
      - name: "\U0001F4D1 Extract total coverage percentage"
        run: |
          coverage_percentage=$(cat ./coverage/index.html | \
          grep -o 'class="strong">[0-9]*% ' | \
          sed 's/class="strong">//g' | \
          awk '{ sum += int($1); count++ } END { if (count > 0) { print sum/count } else { print 0 } }')
          echo "coverage_percentage={\"schemaVersion\": 1, \"label\": \"coverage\", \"message\": \"$coverage_percentage%\", \"color\": \"green\"}" >> "$GITHUB_ENV"
        shell: bash
  display:
    name: Display
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: "⏬ Checkout repository"
        uses: actions/checkout@v3
      - name: "📝 Write percentage to coverage.json"
        run: |
          cd ${{ github.workspace }}
          echo ${{ github.workspace }}
          mkdir -p coverage
          echo ${{ env.coverage_percentage }} > coverage/coverage.json
      - name: "✅ Commit and push changes"
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Update coverage percentage"
